name: "Wails Build"
description: "Cross-compile wails applications"
inputs:
  path:
    description: "The path within the repository to your wails project"
    required: false
  args:
    description: "wails build arguments"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.args }}
