name: Test
on: "push"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "wails-build-action"
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: ./wails-build-action
        with:
          path: "tests/fixtures/test-fixtures"
